# Generated by Django 3.1.7 on 2021-04-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
